### ISSUE TITLE
Does TextureOptions::NEAREST work?

### ISSUE THREAD

**Issue by yds12** [not-fl3/egui-miniquad#55]
I'm trying to use the NEAREST filter for enlarged images, which I show in an ImageButton. The code I use to load the texture is the following:

```
ui.ctx().load_texture("tex", image, egui::TextureOptions::NEAREST)
```

I would expect this to give the "pixelized" effect, but it looks like it's using the LINEAR filter instead (blurry).

Could it be [this line](https://github.com/not-fl3/egui-miniquad/blob/51df1454eed68565d749df8024b8dec9367c5306/src/painter.rs#L128)? It seems that `Linear` is always used:

```
filter: miniquad::FilterMode::Linear,
```

I checked the loaded texture options, and at least according to TextureManager, it seems to be set correctly:

```
let meta = ui.ctx().tex_manager().read().meta(tex.id()).unwrap().options;
dbg!(meta);

// output:
// meta = TextureOptions {
//     magnification: Nearest,
//     minification: Nearest,
// }
```

I'm not sure also if this is the correct place to report this, or if I should open the issue in `egui`. I use `egui-miniquad` as backend (with [`egui-macroquad`](https://github.com/optozorax/egui-macroquad) on top of it, but that's only a few lines of code).

**Comment by Karta775** [comment]
I'm having the same issue, thanks to you I was able to fix it by editing painter.rs and setting `filter` based on what `delta.options.magnification` is set to, so you can effectively specify either `TextureOptions::NEAREST` or `TextureOptions::LINEAR`, but you wouldn't be able to set different behaviour for minification: 
```rust
let filter = match delta.options.magnification {
    TextureFilter::Nearest => FilterMode::Nearest,
    TextureFilter::Linear => FilterMode::Linear,
};
```
I don't know enough about this to say for sure, but it looks like the problem lies with egui providing a texture with separate options for magnification and minification, whereas there's no such distinction with miniquad's FilterMode.

**Comment by yds12** [comment]
Hi @Karta775, thanks for the info. If I may ask, where in `painter.rs` did you make that change? Would you consider maybe opening a PR with it? I'd be very interested in it.

**Comment by yds12** [comment]
Thanks for the PR! I made the change locally here as well and it works.
